server:
  port: 9090
---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  profiles:
    active:
    - dev
  application:
    name: toures-balon-api-gateway
  cloud:
    gateway:
      routes:
      - id: toures-balon-api-gateway-test
        uri: lb://TOURES-BALON-API-GATEWAY-TEST
        predicates:
        - Path=/test/**