server:
  port: 9090
---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  profiles:
    active:
    - dev
  application:
    name: toures-balon-api-gateway
  cloud:
    gateway:
      routes:
      - id: toures-balon-usuario-routes
        uri: lb://TOURES-BALON-USUARIO
        predicates:
        - Path=/usuario/**
 
  